### ISSUE TITLE
Ubuntu下编译Appimage包，运行报错 Cannot read property 'setAlwaysOnTop' of null

### ISSUE THREAD

**Issue by NingerJohn** [c10342/player#11]
1. 环境信息如下
```
$ uanme -a
Linux ninger-MS-7A15 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
2. 报错如下
```javascript
Error
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'setAlwaysOnTop' of null
at EventEmitter.<anonymous> (/tmp/.mount_ playerDl7aFv/resources/app.asar/dist/electron/main.js:1:13829)
at EventEmitter.emit (events.js:182:13)
at WebContents.<anonymous> (/tmp/.mount._playerDl7aFv/resources/electron.asar/browser/api/web-contents.js:346:13) at WebContents.emit (events.js:182:13)
```

**Comment by c10342** [comment]
非常感谢你的反馈，我会尽快修复该问题的
